### ISSUE TITLE
We need to be able to easily create new field types for Sonata Admin

### ISSUE THREAD

**Issue by betaglop** [libre-informatique/SymfonyLibrinfoCoreBundle#2]
If you use an "email" type for a field, it will be rendered as raw text, without any link (anchor tag). It shall be good to add it...

And going further, we will probably need more types... So having a nice feature allowing us to add new types very easily should be an important improvement to Sonata Admin Bundle.

**Comment by betaglop** [comment]
cf. commit 9fe27ea

**Comment by betaglop** [comment]
We are now able to add a new type in two steps (if the fields are already configured correctly in your ```librinfo.yml``` files):

1. adding this type into your ```librinfo.yml``` file
2. (if necessary) creating a new Twig template

e.g.:
1.
```yaml
# Resources/config/librinfo.yml
parameters:
    librinfo:
        configuration:
            templates:
                show:
                    email: LibrinfoCoreBundle:CRUD:list_field_email.html.twig
                list:
                    email: LibrinfoCoreBundle:CRUD:list_field_email.html.twig
```
2.
```twig
{# Resources/views/CRUD/list_field_email.html.twig #}
{#

This file is part of the Sonata package.

(c) Baptiste SIMON <beta@e-glop.net>
(c) Libre Informatique [http://www.libre-informatique.fr/]

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}

{% extends 'SonataAdminBundle:CRUD:base_show_field.html.twig' %}

{% block field %}
<a href="mailto:{{ value }}">{{ value }}</a>
{% endblock %}
```
